/*
 * 公开曲库：不包含任何非公开 App 的平台收藏数据。
 * seedScore 只用于分散热门候选，不在页面展示，也不对应具体播放/收藏数字。
 */
const rawSongs = [
  // 第一张专辑《勇敢额度》
  ["yu-hou-ri-ji", "雨后日记", "album", "solo", "治愈", "专辑《勇敢额度》", 88],
  ["yong-gan-e-du", "勇敢额度", "album", "solo", "流行", "专辑《勇敢额度》", 81],
  ["kong-er", "空耳", "album", "solo", "氛围", "专辑《勇敢额度》", 80],
  ["ling-yi-zhong-da-an", "另一种答案", "album", "solo", "流行", "专辑《勇敢额度》", 69],
  ["tell-me", "Tell Me", "album", "collab", "R&B", "专辑《勇敢额度》", 69],
  ["ni-ming-xing", "匿名星", "album", "solo", "氛围", "专辑《勇敢额度》", 66],
  ["shi-jiao", "失焦", "album", "solo", "情绪", "专辑《勇敢额度》", 66],
  ["forever-in-you", "Forever In You", "album", "collab", "R&B", "专辑《勇敢额度》", 62],
  ["gray-turns-to-may", "Gray Turns To May", "album", "solo", "R&B", "专辑《勇敢额度》", 54],
  ["ni-hao-kuai-le", "你好快乐", "album", "solo", "轻快", "专辑《勇敢额度》", 53],

  // 第二张专辑《纯妹妹》；先行版/正式版同名曲已合并
  ["zhu-yu", "珠玉", "album", "solo", "抒情", "专辑《纯妹妹》", 98],
  ["chun-mei-mei", "纯妹妹", "album", "solo", "轻快", "专辑《纯妹妹》", 98],
  ["wo-guan-bu-zhu-wo-zi-ji", "我管不住我自己", "album", "solo", "情绪", "专辑《纯妹妹》", 92],
  ["hai-you-shen-me-geng-hao-de", "还有什么更好的", "album", "solo", "流行", "专辑《纯妹妹》", 78],
  ["wo-biao-shi-li-jie", "我表示理解", "album", "solo", "情绪", "专辑《纯妹妹》", 76],
  ["you-qu", "有趣", "album", "solo", "轻快", "专辑《纯妹妹》", 76],
  ["xiang-ri-kui-chao-zhe-ye", "向日葵朝着夜", "album", "solo", "叙事", "专辑《纯妹妹》", 70],
  ["huan-ni-mo-li", "还你茉莉", "album", "solo", "国风", "专辑《纯妹妹》", 70],
  ["duo-shao-de-guang-yin", "多少的光阴", "album", "solo", "叙事", "专辑《纯妹妹》", 64],
  ["jia-ru-wo-men-hai-ai-zhe", "假如我们还爱着", "album", "solo", "抒情", "专辑《纯妹妹》", 59],

  // 音乐综艺《歌手2025》（珠玉、有趣的节目版本已按要求移除）
  ["li-bai-live", "李白", "variety", "solo", "摇滚", "综艺《歌手2025》", 93],
  ["jun-live", "君", "variety", "solo", "国风", "综艺《歌手2025》", 84],
  ["luo-ye-gui-gen-live", "落叶归根", "variety", "solo", "抒情", "综艺《歌手2025》", 81],
  ["tian-kong-live", "天空", "variety", "solo", "大气", "综艺《歌手2025》", 76],
  ["kai-shi-dong-le-live", "开始懂了", "variety", "solo", "抒情", "综艺《歌手2025》", 73],
  ["dear-friend-live", "Dear Friend", "variety", "solo", "抒情", "综艺《歌手2025》", 66],
  ["yi-ge-ren-tiao-wu-live", "一个人跳舞", "variety", "solo", "律动", "综艺《歌手2025》", 66],
  ["ai-qing-live", "爱情", "variety", "solo", "抒情", "综艺《歌手2025》", 64],
  ["wu-niang-live", "舞娘", "variety", "solo", "舞曲", "综艺《歌手2025》", 63],
  ["meng-yi-chang-live", "梦一场", "variety", "solo", "叙事", "综艺《歌手2025》", 61],
  ["si-nian-shi-yi-zhong-bing-live", "思念是一种病", "variety", "solo", "律动", "综艺《歌手2025》", 58],

  // OST：出处经公开音乐页面及作品资料核对
  ["xiang-ni-shi-feng-qi", "想你时风起", "ost", "solo", "抒情", "电视剧《我的人间烟火》· 回忆主题曲", 100],
  ["xu-xie", "续写", "ost", "solo", "叙事", "电视剧《一生一世》· 主题曲", 90],
  ["ni-de-zhen-cang", "你的珍藏", "ost", "solo", "治愈", "电影《沐浴之王》· 情感主题曲", 88],
  ["cang-zai-ni-de-ming-zi-li", "藏在你的名字里", "ost", "solo", "抒情", "电影《一闪一闪亮星星》· 主题曲", 87],
  ["xiang-yan-huo-ai-guo", "像烟火爱过", "ost", "solo", "情绪", "电视剧《许我耀眼》· 原声歌曲", 83],
  ["xing-han-can-lan", "星汉灿烂", "ost", "solo", "大气", "电视剧《星汉灿烂》· 主题曲", 82],
  ["ni-shi-dao-ying-de-wei-xing", "你是倒映的微星", "ost", "solo", "抒情", "电视剧《春闺梦里人》· 人物主题曲", 76],
  ["yu-wei", "余味", "ost", "solo", "情绪", "网络剧《七时吉祥》· 沧海缠绵曲", 76],
  ["ying-huo-chong", "萤火虫", "ost", "solo", "治愈", "电影《误杀2》· 片尾曲", 72],
  ["re-tang", "热汤", "ost", "solo", "治愈", "电视剧《假日暖洋洋2》· 片尾曲", 72],
  ["ai-li", "爱里", "ost", "solo", "抒情", "电视剧《我们的翻译官》· 爱情主题曲", 65],
  ["yue-shang-ge", "月上歌", "ost", "solo", "国风", "电视剧《藏海传》· 空灵骊歌", 65],
  ["zai-jian-wang-shi", "再见往事", "ost", "solo", "叙事", "电影《怒潮》· 片尾曲", 65],
  ["ni-de-shi-jie", "你的世界", "ost", "solo", "抒情", "电影《小美人鱼》· 中文主题曲", 55],
  ["fei-cheng-wu-rao", "非诚勿扰", "ost", "solo", "轻快", "电影《非诚勿扰3》· 主题曲", 55],
  ["rang-wo-sui-feng", "让我随风", "ost", "solo", "治愈", "电视剧《三体》· 插曲", 54],
  ["yu-hua", "羽化", "ost", "solo", "大气", "网络剧《虎鹤妖师录》· 插曲", 53],
  ["feng-wu-mian", "风无眠", "ost", "solo", "氛围", "电视剧《长安二十四计》· 主题曲", 52],
  ["zhi", "执", "ost", "solo", "国风", "电视剧《人之初》· 插曲", 51],
  ["qi-cai-guang", "七彩光", "ost", "solo", "明亮", "电影《日掛中天》· 主题曲", 50],
  ["ren-xing", "任性", "ost", "solo", "情绪", "电视剧《斗罗大陆》· 宁荣荣人物曲", 48],
  ["ru-xing", "如星", "ost", "solo", "抒情", "电视剧《奇迹》· 影视原声", 46],
  ["di-yi-ci", "第一次", "ost", "solo", "抒情", "电影《小美人鱼》· 中文插曲", 44],
  ["yi-sheng-yi-nian", "一生一念", "ost", "solo", "国风", "电视剧《祈今朝》· 主题曲", 42],

  // 单曲
  ["zai-ye-li-tiao-wu", "在夜里跳舞", "single", "solo", "律动", "个人数字单曲", 96],
  ["wei", "喂", "single", "solo", "轻快", "个人数字单曲", 90],
  ["ai-wo-de-shi-hou", "爱我的时候", "single", "solo", "抒情", "个人数字单曲", 88],
  ["zhao-pian", "照片", "single", "solo", "叙事", "个人数字单曲", 85],
  ["oh-lala", "Oh lala", "single", "solo", "R&B", "合作企划《DNA》", 72],
  ["tender", "TENDER", "single", "solo", "R&B", "个人数字单曲", 67],
  ["luo-bi-cheng-shu", "落笔成书", "single", "solo", "国风", "个人数字单曲", 66],
  ["zhong-shen-gu-du", "终身孤独", "single", "solo", "情绪", "个人数字单曲", 64],
  ["4ever-in-u", "4ever in U", "single", "collab", "R&B", "合作数字单曲", 64],
  ["fen-shen", "分身", "single", "solo", "情绪", "个人数字单曲", 61],
  ["qi-guan", "奇观", "single", "solo", "大气", "个人数字单曲", 61],
  ["liang-zai-ri-ji", "靓仔日记", "single", "solo", "轻快", "个人数字单曲", 58],
  ["guang-bo", "光波", "single", "solo", "律动", "巡演主题数字单曲", 57],

  // 独唱作品（《如星》已在 OST 分类中收录，不重复添加）
  ["yong-bu-shi-lian-de-ai", "永不失联的爱（正式版）", "single", "solo", "抒情", "个人单曲", 97],
  ["sen-zhi-lian-ge", "森之恋歌", "single", "solo", "治愈", "个人单曲", 91],
  ["xing-mang", "星芒", "single", "solo", "明亮", "个人单曲", 76],
  ["ai-de-qi-huan-lv-xing", "爱的奇幻旅行", "single", "solo", "明亮", "个人单曲", 78],
  ["hong-qing-ting", "红蜻蜓", "single", "solo", "治愈", "个人单曲", 75],
  ["qing-ren", "情人", "single", "solo", "抒情", "个人单曲", 82],
  ["mei-man-yi-sheng", "美满一生", "single", "solo", "治愈", "个人单曲", 73],
  ["chun-mei-mei-sleep", "纯寐寐", "single", "solo", "氛围", "个人单曲", 70],
  ["wo-zai-yi-de", "我在意的", "single", "solo", "抒情", "个人单曲", 72],

  // 合唱作品
  ["deng-ni-lai", "等你来", "single", "collab", "明亮", "个人单曲 · 合唱", 74],
  ["piao-yang-guo-hai-lai-kan-ni", "飘洋过海来看你", "single", "collab", "抒情", "个人单曲 · 合唱", 84],
  ["always-on-my-way", "always on my way", "single", "collab", "R&B", "个人单曲 · 合唱", 76],
  ["sinking", "Sinking", "single", "collab", "R&B", "个人单曲 · 合唱", 75],
  ["yue-liang-wu-tai", "月亮舞台", "single", "collab", "氛围", "个人单曲 · 合唱", 77],
  ["wo-men-xiang-xin", "我们相信", "single", "collab", "大气", "个人单曲 · 合唱", 73],
  ["jian-xin-ru-wu", "见信如晤", "single", "collab", "叙事", "个人单曲 · 合唱", 72],
  ["wu-you-nian", "无忧·念", "single", "collab", "国风", "个人单曲 · 合唱", 70],
  ["bu-ru-jian-yi-mian", "不如见一面", "single", "collab", "抒情", "个人单曲 · 合唱", 81],
  ["wei-wan-dai-xu", "未完待续", "single", "collab", "叙事", "个人单曲 · 合唱", 71],

  // 综艺舞台：2020《中国好声音》
  ["xiang-feng-yi-yang", "像风一样", "variety", "solo", "抒情", "综艺《2020中国好声音》", 88],
  ["forever-young", "Forever Young", "variety", "solo", "明亮", "综艺《2020中国好声音》", 84],
  ["xun-yi-ge-tian-huang-di-lao-de-di-fang", "寻一个天荒地老的地方", "variety", "solo", "抒情", "综艺《2020中国好声音》", 80],
  ["ru-ci", "如此", "variety", "solo", "氛围", "综艺《2020中国好声音》", 78],
  ["ren-a", "人啊", "variety", "solo", "叙事", "综艺《2020中国好声音》", 82],
  ["hao-jiu-bu-jian", "好久不见", "variety", "solo", "抒情", "综艺《2020中国好声音》", 86],
  ["xing-sailing", "星·Sailing", "variety", "solo", "大气", "综艺《2020中国好声音》", 77],

  // 《天赐的声音》
  ["bu-bi-zai-hu-wo-shi-shei", "不必在乎我是谁", "variety", "solo", "抒情", "综艺《天赐的声音》", 78],
  ["xia-yu-tian", "下雨天", "variety", "solo", "抒情", "综艺《天赐的声音》", 80],
  ["gen-ben-bu-shi-wo-dui-shou", "根本不是我对手", "variety", "solo", "律动", "综艺《天赐的声音》", 70],
  ["she-li-duan", "舍离断", "variety", "solo", "国风", "综艺《天赐的声音》", 72],

  ["soap", "Soap", "variety", "solo", "R&B", "综艺《为歌而赞》", 74],

  // 《说唱听我的》
  ["kuai-le-shi-yong-shou-ce", "快乐使用手册", "variety", "collab", "律动", "综艺《说唱听我的》", 74],
  ["shi-guang-dao-xu", "时光·倒叙", "variety", "collab", "叙事", "综艺《说唱听我的》", 71],
  ["po-chen-shan", "破衬衫", "variety", "collab", "律动", "综艺《说唱听我的》", 72],
  ["moon-talk", "Moon Talk", "variety", "collab", "R&B", "综艺《说唱听我的》", 73],
  ["sunrise", "Sunrise", "variety", "collab", "明亮", "综艺《说唱听我的》", 72],

  // 《爆裂舞台》
  ["rnb-all-night", "R&B All Night", "variety", "solo", "R&B", "综艺《爆裂舞台》", 80],
  ["bie-wen-hen-ke-pa", "别问很可怕", "variety", "solo", "情绪", "综艺《爆裂舞台》", 78],
  ["ma-ma-shuo", "妈妈说", "variety", "solo", "律动", "综艺《爆裂舞台》", 75],
  ["get-away", "Get Away", "variety", "solo", "舞曲", "综艺《爆裂舞台》", 76],
  ["bao-lie-zhan-xian-lian-meng", "爆裂战线联盟", "variety", "collab", "舞曲", "综艺《爆裂舞台》", 73],
  ["bu-zhi-de", "不值得", "variety", "solo", "抒情", "综艺《爆裂舞台》", 81],
  ["lang", "狼", "variety", "solo", "摇滚", "综艺《爆裂舞台》", 79],

  // 《我们的歌》
  ["if-only", "If Only", "variety", "collab", "抒情", "综艺《我们的歌》", 77],
  ["zi-you", "自由", "variety", "collab", "摇滚", "综艺《我们的歌》", 76],
  ["fu-er-mo-si", "福尔摩斯", "variety", "collab", "律动", "综艺《我们的歌》", 75],
  ["nv-er-guo", "女儿国", "variety", "collab", "国风", "综艺《我们的歌》", 79],
  ["stand-by-me", "Stand By Me", "variety", "collab", "经典", "综艺《我们的歌》", 76],
  ["ju-gao-zheng", "惧高症", "variety", "collab", "情绪", "综艺《我们的歌》", 74],
  ["ying-di", "影帝", "variety", "collab", "叙事", "综艺《我们的歌》", 75],

  // 《声生不息·港乐季》
  ["ai-yu-tong-de-bian-yuan", "爱与痛的边缘", "variety", "solo", "抒情", "综艺《声生不息·港乐季》", 83],
  ["lai-sheng-yuan", "来生缘", "variety", "collab", "经典", "综艺《声生不息·港乐季》", 78],
  ["gao-shan-di-gu", "高山低谷", "variety", "solo", "叙事", "综艺《声生不息·港乐季》", 82],
  ["san-ren-you", "三人游", "variety", "collab", "R&B", "综艺《声生不息·港乐季》", 80],
  ["fen-fen-zhong-xu-yao-ni", "分分钟需要你", "variety", "collab", "轻快", "综艺《声生不息·港乐季》", 80],
  ["zhe-me-jin-na-me-yuan", "这么近那么远", "variety", "solo", "氛围", "综艺《声生不息·港乐季》", 79],
  ["wei-ni-zhong-qing", "为你钟情", "variety", "collab", "抒情", "综艺《声生不息·港乐季》", 81],
  ["ai-shi-yong-heng", "爱是永恒", "variety", "collab", "大气", "综艺《声生不息·港乐季》", 82],
  ["qian-yi-ge-ye-wan", "千亿个夜晚", "variety", "solo", "经典", "综艺《声生不息·港乐季》", 78],
  ["wang-ji-ta", "忘记他", "variety", "solo", "经典", "综艺《声生不息·港乐季》", 80],
  ["ta-lai-ting-wo-de-yan-chang-hui", "她来听我的演唱会", "variety", "collab", "叙事", "综艺《声生不息·港乐季》", 84],

  // 《剧好听的歌》
  ["rang-ta-jiang-luo", "让她降落", "variety", "solo", "抒情", "综艺《剧好听的歌》", 80],
  ["zui-chang-de-lv-tu", "最长的旅途", "variety", "solo", "叙事", "综艺《剧好听的歌》", 79],
  ["ai-de-hui-gui-xian", "爱的回归线", "variety", "collab", "抒情", "综艺《剧好听的歌》", 81],
  ["xuan-cao-hua", "萱草花", "variety", "solo", "治愈", "综艺《剧好听的歌》", 82],
  ["wo-yao-ni", "我要你", "variety", "solo", "抒情", "综艺《剧好听的歌》", 78],
  ["dian-qi-jiao-jian-ai", "踮起脚尖爱", "variety", "solo", "抒情", "综艺《剧好听的歌》", 83],

  // 《音乐缘计划》与《国乐无双》
  ["tai-yang-gong-zhu", "太阳公主", "variety", "solo", "明亮", "综艺《音乐缘计划》", 78],
  ["ming-zhi-gu-wen", "明知故问", "variety", "solo", "情绪", "综艺《音乐缘计划》", 80],
  ["let-me-go", "Let Me Go", "variety", "solo", "R&B", "综艺《音乐缘计划》", 77],
  ["gan-lan-shu", "橄榄树", "variety", "solo", "经典", "综艺《国乐无双》", 76],

  ["gei-dian-ying-ren-de-qing-shu", "给电影人的情书", "single", "solo", "经典", "个人单曲 · 电影《一秒钟》推广曲", 74]
];

const SOURCE_META = {
  album: { label: "专辑曲", colors: ["#5b21b6", "#a855f7"] },
  single: { label: "单曲", colors: ["#9d174d", "#f472b6"] },
  ost: { label: "OST", colors: ["#1d4ed8", "#8b5cf6"] },
  variety: { label: "综艺", colors: ["#836d42", "#d5bd78"] },
  other: { label: "其他", colors: ["#0f766e", "#22d3ee"] }
};

// 每首歌最多保留一个极短歌词摘录（不超过 10 个词）。
// 人工歌词配置区：每首歌最终都会获得 lyricExcerpt 字段。
// “【待补充高光歌词】”是逐曲占位符，后续直接按歌曲 id 替换即可。
const HIGHLIGHT_LYRICS = {
  "yu-hou-ri-ji": "【待补充高光歌词】",
  "yong-gan-e-du": "【待补充高光歌词】",
  "kong-er": "也许你是我哄我的谎 好借你想起我还有遗憾",
  "ling-yi-zhong-da-an": "【待补充高光歌词】",
  "tell-me": "【待补充高光歌词】",
  "ni-ming-xing": "【待补充高光歌词】",
  "shi-jiao": "【待补充高光歌词】",
  "forever-in-you": "【待补充高光歌词】",
  "gray-turns-to-may": "【待补充高光歌词】",
  "ni-hao-kuai-le": "【待补充高光歌词】",
  "zhu-yu": "她是她",
  "chun-mei-mei": "万物怪可爱",
  "wo-guan-bu-zhu-wo-zi-ji": "其实天地都还在 其实谁都没走开",
  "hai-you-shen-me-geng-hao-de": "落了泪 就升繁华",
  "wo-biao-shi-li-jie": "我们不清不楚地感动 眼眶红过就有始有终",
  "you-qu": "我情愿才敢于 如此专注地欢愉",
  "xiang-ri-kui-chao-zhe-ye": "【待补充高光歌词】",
  "huan-ni-mo-li": "借我借我你的石头 我有蝴蝶还给你",
  "duo-shao-de-guang-yin": "多少的光阴 成全了潮汐的呓语",
  "jia-ru-wo-men-hai-ai-zhe": "假如我还爱着你 我又说远了",
  "li-bai-live": "区区三万天 试试又能怎",
  "jun-live": "我时常时常地想念你 也要泪儿流",
  "luo-ye-gui-gen-live": "【待补充高光歌词】",
  "tian-kong-live": "我们天空 何时才能成一片",
  "kai-shi-dong-le-live": "开始懂了 快乐是选择",
  "dear-friend-live": "世界的绮丽 在我们眼前展开",
  "yi-ge-ren-tiao-wu-live": "我一个人跳舞 从清晨到日暮",
  "ai-qing-live": "若不是因为爱着你 怎会不经意就叹息",
  "wu-niang-live": "旋转跳跃 我闭着眼 尘嚣看不见 你沉醉了没",
  "meng-yi-chang-live": "如梦一场 我又何必把泪 都锁在自己的眼眶",
  "si-nian-shi-yi-zhong-bing-live": "当你在穿山越岭的另一边 我在孤独的路上没有尽头",
  "xiang-ni-shi-feng-qi": "有些远方 让风代替我们抵达 ",
  "xu-xie": "余生续写的诗 每一笔都是你的名字",
  "ni-de-zhen-cang": "【待补充高光歌词】",
  "cang-zai-ni-de-ming-zi-li": "【待补充高光歌词】",
  "xiang-yan-huo-ai-guo": "像烟火爱过",
  "xing-han-can-lan": "【待补充高光歌词】",
  "ni-shi-dao-ying-de-wei-xing": "【待补充高光歌词】",
  "yu-wei": "【待补充高光歌词】",
  "ying-huo-chong": "【待补充高光歌词】",
  "re-tang": "【待补充高光歌词】",
  "ai-li": "【待补充高光歌词】",
  "yue-shang-ge": "捧来当年须臾的月光",
  "zai-jian-wang-shi": "【待补充高光歌词】",
  "ni-de-shi-jie": "【待补充高光歌词】",
  "fei-cheng-wu-rao": "【待补充高光歌词】",
  "rang-wo-sui-feng": "【待补充高光歌词】",
  "yu-hua": "【待补充高光歌词】",
  "feng-wu-mian": "回忆如同逆行的箭",
  "zhi": "【待补充高光歌词】",
  "qi-cai-guang": "看不到的七彩光",
  "ren-xing": "【待补充高光歌词】",
  "ru-xing": "【待补充高光歌词】",
  "di-yi-ci": "【待补充高光歌词】",
  "yi-sheng-yi-nian": "【待补充高光歌词】",
  "zai-ye-li-tiao-wu": "【待补充高光歌词】",
  "wei": "【待补充高光歌词】",
  "ai-wo-de-shi-hou": "【待补充高光歌词】",
  "zhao-pian": "【待补充高光歌词】",
  "oh-lala": "【待补充高光歌词】",
  "tender": "【待补充高光歌词】",
  "luo-bi-cheng-shu": "【待补充高光歌词】",
  "zhong-shen-gu-du": "【待补充高光歌词】",
  "4ever-in-u": "【待补充高光歌词】",
  "fen-shen": "【待补充高光歌词】",
  "qi-guan": "【待补充高光歌词】",
  "liang-zai-ri-ji": "【待补充高光歌词】",
  "guang-bo": "【待补充高光歌词】",
  "yong-bu-shi-lian-de-ai": "【待补充高光歌词】",
  "sen-zhi-lian-ge": "【待补充高光歌词】",
  "xing-mang": "【待补充高光歌词】",
  "ai-de-qi-huan-lv-xing": "【待补充高光歌词】",
  "hong-qing-ting": "【待补充高光歌词】",
  "qing-ren": "【待补充高光歌词】",
  "mei-man-yi-sheng": "【待补充高光歌词】",
  "chun-mei-mei-sleep": "【待补充高光歌词】",
  "wo-zai-yi-de": "【待补充高光歌词】",
  "deng-ni-lai": "【待补充高光歌词】",
  "piao-yang-guo-hai-lai-kan-ni": "【待补充高光歌词】",
  "always-on-my-way": "【待补充高光歌词】",
  "sinking": "【待补充高光歌词】",
  "yue-liang-wu-tai": "【待补充高光歌词】",
  "wo-men-xiang-xin": "【待补充高光歌词】",
  "jian-xin-ru-wu": "【待补充高光歌词】",
  "wu-you-nian": "【待补充高光歌词】",
  "bu-ru-jian-yi-mian": "【待补充高光歌词】",
  "wei-wan-dai-xu": "【待补充高光歌词】",
  "xiang-feng-yi-yang": "【待补充高光歌词】",
  "forever-young": "【待补充高光歌词】",
  "xun-yi-ge-tian-huang-di-lao-de-di-fang": "【待补充高光歌词】",
  "ru-ci": "【待补充高光歌词】",
  "ren-a": "【待补充高光歌词】",
  "hao-jiu-bu-jian": "【待补充高光歌词】",
  "xing-sailing": "【待补充高光歌词】",
  "bu-bi-zai-hu-wo-shi-shei": "【待补充高光歌词】",
  "xia-yu-tian": "【待补充高光歌词】",
  "gen-ben-bu-shi-wo-dui-shou": "【待补充高光歌词】",
  "she-li-duan": "【待补充高光歌词】",
  "soap": "【待补充高光歌词】",
  "kuai-le-shi-yong-shou-ce": "【待补充高光歌词】",
  "shi-guang-dao-xu": "【待补充高光歌词】",
  "po-chen-shan": "【待补充高光歌词】",
  "moon-talk": "【待补充高光歌词】",
  "sunrise": "【待补充高光歌词】",
  "rnb-all-night": "【待补充高光歌词】",
  "bie-wen-hen-ke-pa": "【待补充高光歌词】",
  "ma-ma-shuo": "【待补充高光歌词】",
  "get-away": "【待补充高光歌词】",
  "bao-lie-zhan-xian-lian-meng": "【待补充高光歌词】",
  "bu-zhi-de": "【待补充高光歌词】",
  "lang": "【待补充高光歌词】",
  "if-only": "【待补充高光歌词】",
  "zi-you": "【待补充高光歌词】",
  "fu-er-mo-si": "【待补充高光歌词】",
  "nv-er-guo": "【待补充高光歌词】",
  "stand-by-me": "【待补充高光歌词】",
  "ju-gao-zheng": "【待补充高光歌词】",
  "ying-di": "【待补充高光歌词】",
  "ai-yu-tong-de-bian-yuan": "【待补充高光歌词】",
  "lai-sheng-yuan": "【待补充高光歌词】",
  "gao-shan-di-gu": "【待补充高光歌词】",
  "san-ren-you": "【待补充高光歌词】",
  "fen-fen-zhong-xu-yao-ni": "【待补充高光歌词】",
  "zhe-me-jin-na-me-yuan": "【待补充高光歌词】",
  "wei-ni-zhong-qing": "【待补充高光歌词】",
  "ai-shi-yong-heng": "【待补充高光歌词】",
  "qian-yi-ge-ye-wan": "【待补充高光歌词】",
  "wang-ji-ta": "【待补充高光歌词】",
  "ta-lai-ting-wo-de-yan-chang-hui": "【待补充高光歌词】",
  "rang-ta-jiang-luo": "【待补充高光歌词】",
  "zui-chang-de-lv-tu": "【待补充高光歌词】",
  "ai-de-hui-gui-xian": "【待补充高光歌词】",
  "xuan-cao-hua": "【待补充高光歌词】",
  "wo-yao-ni": "【待补充高光歌词】",
  "dian-qi-jiao-jian-ai": "【待补充高光歌词】",
  "tai-yang-gong-zhu": "【待补充高光歌词】",
  "ming-zhi-gu-wen": "【待补充高光歌词】",
  "let-me-go": "【待补充高光歌词】",
  "gan-lan-shu": "【待补充高光歌词】",
  "gei-dian-ying-ren-de-qing-shu": "【待补充高光歌词】"
};

const MOOD_CUES = {
  治愈: ["让声音把褶皱抚平", "适合安静听完的温度"],
  流行: ["旋律很快留下轮廓", "副歌里藏着情绪出口"],
  氛围: ["留白比答案更清晰", "适合戴上耳机慢慢听"],
  情绪: ["情绪沿着旋律逐层推进", "转折处最容易击中心事"],
  抒情: ["把没有说完的话唱完", "慢下来才听见细节"],
  轻快: ["节拍先一步点亮心情", "轻盈里也藏着小巧思"],
  叙事: ["像翻开一页声音日记", "故事感顺着旋律展开"],
  国风: ["古意与现代声线相遇", "余韵在尾音里慢慢散开"],
  "R&B": ["律动和转音彼此呼应", "适合跟着节拍轻轻摇摆"],
  摇滚: ["力量在层层推进中释放", "现场感让情绪更直接"],
  大气: ["声场一点点向远处打开", "高处的情绪更显辽阔"],
  律动: ["节拍让身体先于思考", "松弛感藏在每次落拍"],
  舞曲: ["舞台能量从第一拍启动", "适合跟着节奏直接进入"],
  明亮: ["旋律里透出一束亮色", "明快之外仍有细腻余味"],
  经典: ["熟悉旋律被唱出新质感", "把旧故事重新交给此刻"]
};

// 同一档音综共用一个本地封面 URL，浏览器只需解码和缓存一张图。
// 专辑曲和单曲仍保留各自封面，避免覆盖先行版、单曲版等差异。
const PROGRAM_COVER_IDS = {
  "综艺《歌手2025》": "li-bai-live",
  "综艺《2020中国好声音》": "xiang-feng-yi-yang",
  "综艺《天赐的声音》": "xia-yu-tian",
  "综艺《为歌而赞》": "soap",
  "综艺《说唱听我的》": "kuai-le-shi-yong-shou-ce",
  "综艺《爆裂舞台》": "rnb-all-night",
  "综艺《我们的歌》": "fu-er-mo-si",
  "综艺《声生不息·港乐季》": "ai-yu-tong-de-bian-yuan",
  "综艺《剧好听的歌》": "rang-ta-jiang-luo",
  "综艺《音乐缘计划》": "let-me-go",
  "综艺《国乐无双》": "gan-lan-shu"
};

window.SONG_CATALOG = rawSongs.map((row, index) => {
  const [id, title, source, vocal, mood, release, seedScore] = row;
  const color = SOURCE_META[source]?.colors || SOURCE_META.other.colors;
  const lyricExcerpt = HIGHLIGHT_LYRICS[id] || "";
  return {
    id,
    title,
    source,
    sourceLabel: SOURCE_META[source]?.label || "其他",
    vocal,
    vocalLabel: vocal === "collab" ? "合作" : "独唱",
    mood,
    release,
    seedScore,
    cover: `assets/covers/${PROGRAM_COVER_IDS[release] || id}.jpg`,
    lyricExcerpt,
    cardTextKind: lyricExcerpt ? "歌词短摘" : "听感提示",
    cardLines: lyricExcerpt ? [lyricExcerpt] : (MOOD_CUES[mood] || ["把注意力交给旋律", "听见属于它的独特颜色"]),
    quote: `这一刻，我把偏爱留给《${title}》。`,
    colors: index % 2 ? color : [color[1], color[0]]
  };
});

window.SONG_META = {
  source: Object.fromEntries(Object.entries(SOURCE_META).map(([key, value]) => [key, value.label])),
  vocal: { solo: "独唱", collab: "合作" }
};
