/*
 * 公开曲库：不包含任何非公开 App 的平台收藏数据。
 * seedScore 只用于分散热门候选，不在页面展示，也不对应具体播放/收藏数字。
 */
const rawSongs = [
  // 第一张专辑《勇敢额度》
  ["yu-hou-ri-ji", "雨后日记", "album", "solo", "治愈", "专辑《勇敢额度》", 88],
  ["yong-gan-e-du", "勇敢额度", "album", "solo", "流行", "专辑《勇敢额度》", 81],
  ["kong-er", "空耳", "album", "solo", "氛围", "专辑《勇敢额度》", 80],
  ["ling-yi-zhong-da-an", "另一种答案", "album", "solo", "流行", "专辑《勇敢额度》", 69],
  ["tell-me", "Tell Me", "album", "collab", "R&B", "专辑《勇敢额度》", 69],
  ["ni-ming-xing", "匿名星", "album", "solo", "氛围", "专辑《勇敢额度》", 66],
  ["shi-jiao", "失焦", "album", "solo", "情绪", "专辑《勇敢额度》", 66],
  ["forever-in-you", "Forever In You", "album", "collab", "R&B", "专辑《勇敢额度》", 62],
  ["gray-turns-to-may", "Gray Turns To May", "album", "solo", "R&B", "专辑《勇敢额度》", 54],
  ["ni-hao-kuai-le", "你好快乐", "album", "solo", "轻快", "专辑《勇敢额度》", 53],

  // 第二张专辑《纯妹妹》；先行版/正式版同名曲已合并
  ["zhu-yu", "珠玉", "album", "solo", "抒情", "专辑《纯妹妹》", 98],
  ["chun-mei-mei", "纯妹妹", "album", "solo", "轻快", "专辑《纯妹妹》", 98],
  ["wo-guan-bu-zhu-wo-zi-ji", "我管不住我自己", "album", "solo", "情绪", "专辑《纯妹妹》", 92],
  ["hai-you-shen-me-geng-hao-de", "还有什么更好的", "album", "solo", "流行", "专辑《纯妹妹》", 78],
  ["wo-biao-shi-li-jie", "我表示理解", "album", "solo", "情绪", "专辑《纯妹妹》", 76],
  ["you-qu", "有趣", "album", "solo", "轻快", "专辑《纯妹妹》", 76],
  ["xiang-ri-kui-chao-zhe-ye", "向日葵朝着夜", "album", "solo", "叙事", "专辑《纯妹妹》", 70],
  ["huan-ni-mo-li", "还你茉莉", "album", "solo", "国风", "专辑《纯妹妹》", 70],
  ["duo-shao-de-guang-yin", "多少的光阴", "album", "solo", "叙事", "专辑《纯妹妹》", 64],
  ["jia-ru-wo-men-hai-ai-zhe", "假如我们还爱着", "album", "solo", "抒情", "专辑《纯妹妹》", 59],

  // 单曲
  ["zai-ye-li-tiao-wu", "在夜里跳舞", "single", "solo", "律动", "个人单曲", 96],
  ["wei", "喂", "single", "solo", "轻快", "个人单曲", 90],
  ["ai-wo-de-shi-hou", "爱我的时候", "single", "collab", "抒情", "个人单曲", 88],
  ["zhao-pian", "照片", "single", "solo", "叙事", "个人单曲", 85],
  ["oh-lala", "Oh lala", "single", "solo", "R&B", "合作企划《DNA》", 72],
  ["4ever-in-u", "4ever in U", "single", "solo", "R&B", "合作数字单曲", 64],
  ["fen-shen", "分身", "single", "solo", "情绪", "个人单曲", 61],
  ["qi-guan", "奇观", "single", "solo", "大气", "个人单曲", 61],
  ["liang-zai-ri-ji", "靓仔日记", "single", "solo", "轻快", "个人单曲", 58],
  ["guang-bo", "光波", "single", "solo", "律动", "巡演主题数字单曲", 57],
  ["jun-live", "君", "single", "solo", "国风", "个人单曲", 84],
  ["chun-mei-mei-sleep", "纯寐寐", "single", "solo", "氛围", "个人单曲", 70],
  ["tong-xin-xiang-wei-lai", "同心向未来", "single", "solo", "明亮", "个人单曲", 72],
  ["xing-mang", "星芒", "single", "solo", "明亮", "个人单曲", 76],
  ["shan-li-de-yang-guang", "山里的阳光", "single", "solo", "治愈", "个人单曲", 70],
  ["qing-ren", "情人", "single", "solo", "抒情", "个人单曲", 82],
  ["always-on-my-way", "always on my way", "single", "collab", "R&B", "个人单曲 · 合唱", 76],
  ["sinking", "Sinking", "single", "collab", "R&B", "个人单曲 · 合唱", 75],

  // OST：出处经公开音乐页面及作品资料核对
  ["xiang-ni-shi-feng-qi", "想你时风起", "ost", "solo", "抒情", "电视剧《我的人间烟火》· 回忆主题曲", 100],
  ["xu-xie", "续写", "ost", "solo", "叙事", "电视剧《一生一世》· 主题曲", 90],
  ["ni-de-zhen-cang", "你的珍藏", "ost", "solo", "治愈", "电影《沐浴之王》· 情感主题曲", 88],
  ["cang-zai-ni-de-ming-zi-li", "藏在你的名字里", "ost", "solo", "抒情", "电影《一闪一闪亮星星》· 主题曲", 87],
  ["xiang-yan-huo-ai-guo", "像烟火爱过", "ost", "solo", "情绪", "电视剧《许我耀眼》· 原声歌曲", 83],
  ["xing-han-can-lan", "星汉灿烂", "ost", "solo", "大气", "电视剧《星汉灿烂》· 主题曲", 82],
  ["ni-shi-dao-ying-de-wei-xing", "你是倒映的微星", "ost", "solo", "抒情", "电视剧《春闺梦里人》· 人物主题曲", 76],
  ["yu-wei", "余味", "ost", "solo", "情绪", "网络剧《七时吉祥》· 沧海缠绵曲", 76],
  ["ying-huo-chong", "萤火虫", "ost", "solo", "治愈", "电影《误杀2》· 片尾曲", 72],
  ["re-tang", "热汤", "ost", "solo", "治愈", "电视剧《假日暖洋洋2》· 片尾曲", 72],
  ["ai-li", "爱里", "ost", "solo", "抒情", "电视剧《我们的翻译官》· 爱情主题曲", 65],
  ["yue-shang-ge", "月上歌", "ost", "solo", "国风", "电视剧《藏海传》· 空灵骊歌", 65],
  ["zai-jian-wang-shi", "再见往事", "ost", "solo", "叙事", "电影《怒潮》· 片尾曲", 65],
  ["ni-de-shi-jie", "你的世界", "ost", "solo", "抒情", "电影《小美人鱼》· 中文主题曲", 55],
  ["fei-cheng-wu-rao", "非诚勿扰", "ost", "solo", "轻快", "电影《非诚勿扰3》· 主题曲", 55],
  ["rang-wo-sui-feng", "让我随风", "ost", "solo", "治愈", "电视剧《三体》· 插曲", 54],
  ["yu-hua", "羽化", "ost", "solo", "大气", "网络剧《虎鹤妖师录》· 插曲", 53],
  ["feng-wu-mian", "风无眠", "ost", "solo", "氛围", "电视剧《长安二十四计》· 主题曲", 52],
  ["zhi", "执", "ost", "solo", "国风", "电视剧《人之初》· 插曲", 51],
  ["qi-cai-guang", "七彩光", "ost", "solo", "明亮", "电影《日掛中天》· 主题曲", 50],
  ["ren-xing", "任性", "ost", "solo", "情绪", "电视剧《斗罗大陆》· 宁荣荣人物曲", 48],
  ["ru-xing", "如星", "ost", "solo", "抒情", "电视剧《奇迹》· 影视原声", 46],
  ["di-yi-ci", "第一次", "ost", "solo", "抒情", "电影《小美人鱼》· 中文插曲", 44],
  ["yi-sheng-yi-nian", "一生一念", "ost", "solo", "国风", "电视剧《祈今朝》· 主题曲", 42],
  ["gei-dian-ying-ren-de-qing-shu", "给电影人的情书", "ost", "solo", "经典", "电影《一秒钟》· 推广曲", 74],
  ["yong-bu-shi-lian-de-ai", "永不失联的爱", "ost", "solo", "抒情", "《明天你是否依然爱我》电影推广曲", 97],
  ["sen-zhi-lian-ge", "森之恋歌", "ost", "solo", "治愈", "《和平精英》森之鹿灵印象曲", 91],
  ["ai-de-qi-huan-lv-xing", "爱的奇幻旅行", "ost", "solo", "明亮", "襄阳华侨城·奇幻谷主题曲", 78],
  ["wo-zai-yi-de", "我在意的", "ost", "solo", "抒情", "《爱情有烟火》电视剧主题曲", 72],
  ["mei-man-yi-sheng", "美满一生", "ost", "solo", "治愈", "2025中秋主题歌曲", 73],
  ["hong-qing-ting", "红蜻蜓", "ost", "solo", "治愈", "《人生路不熟》电影特别歌谣", 75],
  ["piao-yang-guo-hai-lai-kan-ni", "飘洋过海来看你", "ost", "collab", "抒情", "《合法伴侣》电影推广曲", 84],
  ["wo-men-xiang-xin", "我们相信", "ost", "collab", "大气", "第十五届海峡论坛· 主题歌", 73],
  ["wu-you-nian", "无忧·念", "ost", "collab", "国风", "《无忧渡》影视剧片尾曲", 70],
  ["wei-wan-dai-xu", "未完待续", "ost", "collab", "叙事", "《王者荣耀》520心动手记主题曲", 71],

  // 晚会舞台
  ["zhe-shi-jie-na-me-duo-ren", "这世界那么多人", "live", "collab", "抒情", "晚会舞台", 81],
  ["this-is-me", "This is me", "live", "solo", "大气", "晚会舞台", 78],
  ["gui", "归", "live", "solo", "国风", "晚会舞台", 77],
  ["ru-yuan", "如愿", "live", "solo", "大气", "晚会舞台", 84],
  ["yi-zhi-hen-an-jing", "一直很安静", "live", "solo", "抒情", "晚会舞台", 82],
  ["si-nian", "思念", "live", "solo", "情绪", "晚会舞台", 79],
  ["xin-huo", "心火", "live", "collab", "情绪", "晚会舞台", 78],
  ["cheng-shi-zhi-guang", "城市之光", "live", "solo", "明亮", "晚会舞台", 76],
  ["ni-jiu-bu-yao-xiang-qi-wo", "你就不要想起我", "live", "solo", "抒情", "晚会舞台", 83],
  ["dong-bei-min-yao", "东北民谣", "live", "collab", "叙事", "晚会舞台", 80],
  ["tian-tian", "天天", "live", "collab", "轻快", "晚会舞台", 79],
  ["xiang-si", "相思", "live", "collab", "国风", "晚会舞台", 78],
  ["tian-di-long-lin", "天地龙鳞", "live", "collab", "大气", "晚会舞台", 77],
  ["song-ni-yi-duo-xiao-hong-hua", "送你一朵小红花", "live", "collab", "治愈", "晚会舞台", 78],
  ["feng-xian", "奉献", "live", "collab", "经典", "晚会舞台", 76],
  ["yi-dong-de-xin", "驿动的心", "live", "collab", "经典", "晚会舞台", 76],
  ["fei-yun-zhi-xia", "飞云之下", "live", "collab", "大气", "晚会舞台", 82],
  ["tui-kai-shi-jie-de-men", "推开世界的门", "live", "collab", "治愈", "晚会舞台", 81],
  ["yun-yu-hai", "云与海", "live", "collab", "抒情", "晚会舞台", 80],
  ["jian-xin-ru-wu", "见信如晤", "live", "collab", "叙事", "晚会舞台", 72],
  ["bu-ru-jian-yi-mian", "不如见一面", "live", "collab", "抒情", "晚会舞台", 81],
  ["yue-liang-wu-tai", "月亮舞台", "live", "collab", "氛围", "晚会舞台", 77],

  // 演唱会舞台
  ["weak-live", "Weak", "live", "solo", "R&B", "演唱会", 76],
  ["pu-tong-peng-you-live", "普通朋友", "live", "solo", "R&B", "演唱会", 80],
  ["er-shi-er-cai-er-shi-san-live", "二十二+才二十三", "live", "solo", "叙事", "演唱会", 78],
  ["tian-ya-ge-nv-live", "天涯歌女", "live", "solo", "经典", "演唱会", 77],
  ["wang-shi-zhi-neng-hui-wei-live", "往事只能回味", "live", "solo", "经典", "演唱会", 77],
  ["shou-zi-live", "瘦子", "live", "solo", "律动", "演唱会", 75],
  ["ye-jian-you-yong-chi-live", "夜间游泳池", "live", "collab", "氛围", "演唱会", 79],

  // 综艺舞台：2020《中国好声音》
  ["xiang-feng-yi-yang", "像风一样", "variety", "solo", "抒情", "综艺《2020中国好声音》", 88],
  ["forever-young", "Forever Young", "variety", "solo", "明亮", "综艺《2020中国好声音》", 84],
  ["xun-yi-ge-tian-huang-di-lao-de-di-fang", "寻一个天荒地老的地方", "variety", "solo", "抒情", "综艺《2020中国好声音》", 80],
  ["ru-ci", "如此", "variety", "solo", "氛围", "综艺《2020中国好声音》", 78],
  ["ren-a", "人啊", "variety", "solo", "叙事", "综艺《2020中国好声音》", 82],
  ["hao-jiu-bu-jian", "好久不见", "variety", "solo", "抒情", "综艺《2020中国好声音》", 86],
  ["xing-sailing", "星·Sailing", "variety", "solo", "大气", "综艺《2020中国好声音》", 77],

  // 《天赐的声音》
  ["bu-bi-zai-hu-wo-shi-shei", "不必在乎我是谁", "variety", "collab", "抒情", "综艺《天赐的声音》", 78],
  ["xia-yu-tian", "下雨天", "variety", "solo", "抒情", "综艺《天赐的声音》", 80],
  ["gen-ben-bu-shi-wo-dui-shou", "根本不是我对手", "variety", "collab", "律动", "综艺《天赐的声音》", 70],
  ["she-li-duan", "舍离断", "variety", "collab", "国风", "综艺《天赐的声音》", 72],
  ["yuan-liang", "原谅", "variety", "collab", "抒情", "综艺《天赐的声音》", 82],

  // 《为歌而赞》
  ["soap", "Soap", "variety", "solo", "R&B", "综艺《为歌而赞》", 74],

  // 《说唱听我的》
  ["kuai-le-shi-yong-shou-ce", "快乐使用手册", "variety", "collab", "律动", "综艺《说唱听我的》", 74],
  ["po-chen-shan", "破衬衫", "variety", "collab", "律动", "综艺《说唱听我的》", 72],
  ["moon-talk", "Moon Talk", "variety", "collab", "R&B", "综艺《说唱听我的》", 73],
  ["sunrise", "Sunrise", "variety", "collab", "明亮", "综艺《说唱听我的》", 72],

  // 《爆裂舞台》
  ["rnb-all-night", "R&B All Night", "variety", "solo", "R&B", "综艺《爆裂舞台》", 80],
  ["bie-wen-hen-ke-pa", "别问很可怕", "variety", "solo", "情绪", "综艺《爆裂舞台》", 78],
  ["ma-ma-shuo", "妈妈说", "variety", "collab", "律动", "综艺《爆裂舞台》", 75],
  ["get-away", "Get Away", "variety", "collab", "舞曲", "综艺《爆裂舞台》", 76],
  ["bu-zhi-de", "不值得", "variety", "solo", "抒情", "综艺《爆裂舞台》", 81],
  ["lang", "狼", "variety", "solo", "摇滚", "综艺《爆裂舞台》", 79],

  // 《我们的歌》
  ["if-only", "If Only", "variety", "collab", "抒情", "综艺《我们的歌》", 77],
  ["zi-you", "自由", "variety", "collab", "摇滚", "综艺《我们的歌》", 76],
  ["fu-er-mo-si", "福尔摩斯", "variety", "collab", "律动", "综艺《我们的歌》", 75],
  ["nv-er-guo", "女儿国", "variety", "collab", "国风", "综艺《我们的歌》", 79],
  ["stand-by-me", "Stand By Me", "variety", "collab", "经典", "综艺《我们的歌》", 76],
  ["ju-gao-zheng", "惧高症", "variety", "collab", "情绪", "综艺《我们的歌》", 74],
  ["ying-di", "影帝", "variety", "collab", "叙事", "综艺《我们的歌》", 75],

  // 《声生不息·港乐季》
  ["ai-yu-tong-de-bian-yuan", "爱与痛的边缘", "variety", "solo", "抒情", "综艺《声生不息·港乐季》", 83],
  ["lai-sheng-yuan", "来生缘", "variety", "collab", "经典", "综艺《声生不息·港乐季》", 78],
  ["gao-shan-di-gu", "高山低谷", "variety", "collab", "叙事", "综艺《声生不息·港乐季》", 82],
  ["san-ren-you", "三人游", "variety", "collab", "R&B", "综艺《声生不息·港乐季》", 80],
  ["fen-fen-zhong-xu-yao-ni", "分分钟需要你", "variety", "collab", "轻快", "综艺《声生不息·港乐季》", 80],
  ["zhe-me-jin-na-me-yuan", "这么近那么远", "variety", "collab", "氛围", "综艺《声生不息·港乐季》", 79],
  ["wei-ni-zhong-qing", "为你钟情", "variety", "collab", "抒情", "综艺《声生不息·港乐季》", 81],
  ["ai-shi-yong-heng", "爱是永恒", "variety", "collab", "大气", "综艺《声生不息·港乐季》", 82],
  ["qian-yi-ge-ye-wan", "千亿个夜晚", "variety", "collab", "经典", "综艺《声生不息·港乐季》", 78],
  ["ta-lai-ting-wo-de-yan-chang-hui", "她来听我的演唱会", "variety", "collab", "叙事", "综艺《声生不息·港乐季》", 84],
  ["ru-guo-ai-wang-le", "如果爱忘了", "variety", "collab", "抒情", "综艺《声生不息·家年华》", 84],

  // 《剧好听的歌》
  ["rang-ta-jiang-luo", "让她降落", "variety", "solo", "抒情", "综艺《剧好听的歌》", 80],
  ["zui-chang-de-lv-tu", "最长的旅途", "variety", "solo", "叙事", "综艺《剧好听的歌》", 79],
  ["ai-de-hui-gui-xian", "爱的回归线", "variety", "solo", "抒情", "综艺《剧好听的歌》", 81],
  ["xuan-cao-hua", "萱草花", "variety", "solo", "治愈", "综艺《剧好听的歌》", 82],
  ["wo-yao-ni", "我要你", "variety", "solo", "抒情", "综艺《剧好听的歌》", 78],
  ["dian-qi-jiao-jian-ai", "踮起脚尖爱", "variety", "solo", "抒情", "综艺《剧好听的歌》", 83],

  // 《音乐缘计划》
  ["tai-yang-gong-zhu", "太阳公主", "variety", "solo", "明亮", "综艺《音乐缘计划》", 78],
  ["ming-zhi-gu-wen", "明知故问", "variety", "collab", "情绪", "综艺《音乐缘计划》", 80],
  ["let-me-go", "Let Me Go", "variety", "solo", "R&B", "综艺《音乐缘计划》", 77],
  ["tender", "TENDER", "variety", "solo", "R&B", "综艺《音乐缘计划》", 67],
  ["luo-bi-cheng-shu", "落笔成书", "variety", "solo", "国风", "综艺《音乐缘计划》", 66],
  ["zhong-shen-gu-du", "终身孤独", "variety", "solo", "情绪", "综艺《音乐缘计划》", 64],
  
  // 《国乐无双》
  ["gan-lan-shu", "橄榄树", "variety", "solo", "经典", "综艺《国乐无双》", 76],

  // 音乐综艺《歌手2025》（珠玉、有趣的节目版本已按要求移除）
  ["li-bai-live", "李白", "variety", "solo", "摇滚", "综艺《歌手2025》", 93],
  ["luo-ye-gui-gen-live", "落叶归根", "variety", "solo", "抒情", "综艺《歌手2025》", 81],
  ["tian-kong-live", "天空", "variety", "solo", "大气", "综艺《歌手2025》", 76],
  ["kai-shi-dong-le-live", "开始懂了", "variety", "solo", "抒情", "综艺《歌手2025》", 73],
  ["dear-friend-live", "Dear Friend", "variety", "solo", "抒情", "综艺《歌手2025》", 66],
  ["yi-ge-ren-tiao-wu-live", "一个人跳舞", "variety", "solo", "律动", "综艺《歌手2025》", 66],
  ["ai-qing-live", "爱情", "variety", "solo", "抒情", "综艺《歌手2025》", 64],
  ["wu-niang-live", "舞娘", "variety", "solo", "舞曲", "综艺《歌手2025》", 63],
  ["meng-yi-chang-live", "梦一场", "variety", "solo", "叙事", "综艺《歌手2025》", 61],
  ["si-nian-shi-yi-zhong-bing-live", "思念是一种病", "variety", "solo", "律动", "综艺《歌手2025》", 58],

];

const SOURCE_META = {
  album: { label: "专辑曲", colors: ["#5b21b6", "#a855f7"] },
  single: { label: "单曲", colors: ["#9d174d", "#f472b6"] },
  ost: { label: "OST", colors: ["#1d4ed8", "#8b5cf6"] },
  variety: { label: "综艺", colors: ["#836d42", "#d5bd78"] },
  live: { label: "现场", colors: ["#be466c", "#f59a5b"] },
  other: { label: "其他", colors: ["#0f766e", "#22d3ee"] }
};

// 每首歌最多保留一个极短歌词摘录（不超过 10 个词）。
// 人工歌词配置区：每首歌最终都会获得 lyricExcerpt 字段。
// “【待补充高光歌词】”是逐曲占位符，后续直接按歌曲 id 替换即可。
const HIGHLIGHT_LYRICS = {
  "yu-hou-ri-ji": "Everything feels like a movie\n围绕我们的对手戏",
  "yong-gan-e-du": "我逐字逐句怯懦 把勇敢一丝一缕消磨",
  "kong-er": "也许你是我哄我的谎 好借你想起我还有遗憾",
  "ling-yi-zhong-da-an": "我穿过汹涌的人海 我穿过云层里的山脉",
  "tell-me": "Tell me how will I know",
  "ni-ming-xing": "我是谁独一无二的星星 谁缠绕我的宿命",
  "shi-jiao": "多可恨的心有灵犀 连我的沉默你都不好奇",
  "forever-in-you": "The rivers of your heart \nI wanna swim",
  "gray-turns-to-may": "This way in may babe \nGo where the stars play",
  "ni-hao-kuai-le": "你好快乐 用我的快乐",
  "zhu-yu": "每想到一些 天地都容纳不下的说法\n心里就烧起烟霞",
  "chun-mei-mei": "可爱可爱 有花就开",
  "wo-guan-bu-zhu-wo-zi-ji": "其实天地都还在 其实谁都没走开",
  "hai-you-shen-me-geng-hao-de": "落了泪 就升繁花",
  "wo-biao-shi-li-jie": "我们不清不楚地感动 眼眶红过就有始有终",
  "you-qu": "我情愿才敢于 如此专注地欢愉",
  "xiang-ri-kui-chao-zhe-ye": "蔚蓝的天我要飞得很远 飞到盼望的人看不见",
  "huan-ni-mo-li": "借我借我你的石头 我有蝴蝶还给你",
  "duo-shao-de-guang-yin": "多少的光阴 成全了潮汐的呓语",
  "jia-ru-wo-men-hai-ai-zhe": "假如我还爱着你 我又说远了",
  "li-bai-live": "区区三万天 试试又能怎",
  "jun-live": "我时常时常地想念你 也要泪儿流",
  "luo-ye-gui-gen-live": "而我却像落叶归根 坠在你心间",
  "tian-kong-live": "我们天空 何时才能成一片",
  "kai-shi-dong-le-live": "开始懂了 快乐是选择",
  "dear-friend-live": "世界的绮丽 在我们眼前展开",
  "yi-ge-ren-tiao-wu-live": "我一个人跳舞 从清晨到日暮",
  "ai-qing-live": "若不是因为爱着你 怎会不经意就叹息",
  "wu-niang-live": "旋转跳跃我闭着眼 尘嚣看不见你沉醉了没",
  "meng-yi-chang-live": "如梦一场 我又何必把泪 都锁在自己的眼眶",
  "si-nian-shi-yi-zhong-bing-live": "当你在穿山越岭的另一边 \n我在孤独的路上没有尽头",
  "xiang-ni-shi-feng-qi": "有些远方 让风代替我们抵达 ",
  "xu-xie": "余生续写的诗 每一笔都是你的名字",
  "ni-de-zhen-cang": "小鸟才相信自己能够飞翔",
  "cang-zai-ni-de-ming-zi-li": "一闪一闪亮晶晶 宇宙在替我回应",
  "xiang-yan-huo-ai-guo": "像烟火爱过 奔向星空 不怕痛",
  "xing-han-can-lan": "沧海 醒过来 多少碑林似山脉",
  "ni-shi-dao-ying-de-wei-xing": "你是倒映的微星 可望不可及的影",
  "yu-wei": "似露又似电 似无暇的美\n似误难辨是非",
  "ying-huo-chong": "穿过风穿过雨 你的天空终会晴朗",
  "re-tang": "飞到远方飞到远方 还好你说的还好我没忘",
  "ai-li": "Embraced by love 听见你的气息",
  "yue-shang-ge": "我要赶在长路之前 捧来当年须臾的月光",
  "zai-jian-wang-shi": "苍穹之下总有最勇敢的人",
  "ni-de-shi-jie": "一起漫步一起歌唱 整日沐浴着温暖阳光",
  "fei-cheng-wu-rao": "也许时光一直追着我们跑",
  "rang-wo-sui-feng": "知识也沉沦 孤独的旅程",
  "yu-hua": "眺望天之涯 离人放不下\n没说完的话 还在心喧哗",
  "feng-wu-mian": "追叹 岁月转眼隐入了尘烟",
  "zhi": "一回眸 谁不是赴宴赴死客\n才懂人之初时哭声为何",
  "qi-cai-guang": "叹息着明媚 空无着生辉",
  "ren-xing": "是冥冥注定 我悠悠地飞行",
  "ru-xing": "梦 去未来 看奇迹 亮如星",
  "di-yi-ci": "当我第一次徘徊 第一次期待",
  "yi-sheng-yi-nian": "许你一生一世亦嗔亦痴的年华\n换你前尘往事湮没于喧哗",
  "zai-ye-li-tiao-wu": "在夜里跳舞 我不想要所有不属于我的归宿",
  "wei": "心中有贼 心如止水 像两种极端在媲美",
  "ai-wo-de-shi-hou": "你付出爱我的时候 拥抱你的人还是我",
  "zhao-pian": "我们拍过的一张张照片 都印在我脑海里面",
  "oh-lala": "Oh NaNaNa",
  "tender": "Oh baby you can tell me \n说出你未满的愿望",
  "luo-bi-cheng-shu": "爱过的当初 来不及落笔成书",
  "zhong-shen-gu-du": "不懂爱为何物 却对它趋之若鹜\n任由妒火一寸寸燃过我皮肤",
  "4ever-in-u": "The rhythms of your heart \nconnect to me",
  "fen-shen": "人的成长不过就是 用心交换阵痛一场",
  "qi-guan": "爱是不属于此的奇观 蜃楼只可以远远观看",
  "liang-zai-ri-ji": "如果可以倒流时光 人生故事可以再写一趟",
  "guang-bo": "初见你的小山坡 烟火不算多\n 它却推过月落 背过雪朵 声息不移",
  "yong-bu-shi-lian-de-ai": "你给我这一辈子都不想失联的爱\n就算你的呼吸远在千山之外",
  "sen-zhi-lian-ge": "你穿越多少时间 跨越多少空间\n来到我身边",
  "xing-mang": "我愿做星芒 闪耀九州之上",
  "ai-de-qi-huan-lv-xing": "地球是蓝水晶 送给你写下一生的约定",
  "hong-qing-ting": "晚霞中的红蜻蜓呀 你在哪里啊",
  "qing-ren": "是缘是情是童真 还是意外\n有泪有罪有付出 还有忍耐",
  "mei-man-yi-sheng": "月光照亮归家的梦 也照亮前程\n照你我所盼的人 美满一生",
  "chun-mei-mei-sleep": "好明媚 没寐美玫眉",
  "wo-zai-yi-de": "那些神话情话表白的话 像深夜一场烟花",
  "piao-yang-guo-hai-lai-kan-ni": "为你我用了半年的积蓄 飘洋过海来看你",
  "always-on-my-way": "真挚灵魂不追随 任人摆弄的傀儡\n穿透彼此心交汇",
  "sinking": "Got me dreaming dreaming dreaming",
  "yue-liang-wu-tai": "唱到花儿都开了 唱到希望满山冈",
  "wo-men-xiang-xin": "你也相信我也相信 心的彼岸有人等着你",
  "jian-xin-ru-wu": "愿情落一笔有挥毫之地 在寻常风景在流转四季",
  "wu-you-nian": "若是无忧念 怎会留下星辉照亮人间",
  "bu-ru-jian-yi-mian": "不如见一面 哪怕是一眼",
  "wei-wan-dai-xu": "在蔚蓝的尽头 未完待续的梦",
  "tong-xin-xiang-wei-lai": "我相信你 就像你相信我一样",
  "shan-li-de-yang-guang": "迎着晨辉上学校 心情多美好",
  "dong-bei-min-yao": "塞北残阳是她的红妆",
  "tian-tian": "我想要天天说 天天说",
  "xiang-si": "最不屑一顾是相思",
  "tian-di-long-lin": "这龙鳞却曾经 铿锵落地犹如碎冰",
  "song-ni-yi-duo-xiao-hong-hua": "送你一朵小红花 开在那牛羊遍野的天涯",
  "feng-xian": "长路奉献给远方 玫瑰奉献给爱情",
  "yi-dong-de-xin": "曾经以为我的家 是一张张的票根",
  "fei-yun-zhi-xia": "在飞云之下 以为忘了的家",
  "tui-kai-shi-jie-de-men": "左手的泥呀 右手的泥呀 知己的花衣裳",
  "yun-yu-hai": "如果世间万物能跨越能相爱",
  "weak-live": "I get so weak in the knees",
  "pu-tong-peng-you-live": "我不能只是 be your friend",
  "er-shi-er-cai-er-shi-san-live": "她今年农历三月六号刚满二十二",
  "tian-ya-ge-nv-live": "天涯呀海角 觅呀觅知音",
  "wang-shi-zhi-neng-hui-wei-live": "时光一逝永不回 往事只能回味",
  "shou-zi-live": "越是不吃越是不想吃 镜中的瘦子我不认识",
  "ye-jian-you-yong-chi-live": "暂时 让外面都与他无关",
  "yuan-liang": "那些日子你会不会舍不得",
  "ru-guo-ai-wang-le": "如果爱忘了 泪不想落下",
  "zhe-shi-jie-na-me-duo-ren": "这世界有那么多人 多幸运我有个我们",
  "this-is-me": "I am brave I am bruised",
  "gui": "是你望着我 你望着我",
  "ru-yuan": "而我将爱你所爱的人间",
  "yi-zhi-hen-an-jing": "给你的爱一直很安静",
  "si-nian": "为何你一去别无消息 只把思念积压在我心头",
  "xin-huo": "因为我曾经和恶魔 斗过几回合\n就算它极端恐吓 不握手言和",
  "cheng-shi-zhi-guang": "当那乌云遮挡月光 城市之光更明亮",
  "ni-jiu-bu-yao-xiang-qi-wo": "明明你也很爱我 没理由爱不到结果",
  "xiang-feng-yi-yang": "你不就像风一样 侵略时沙沙作响",
  "forever-young": "遇到每个女孩我都会告诉她\n你该那样爱上forever young",
  "xun-yi-ge-tian-huang-di-lao-de-di-fang": "在山的怀抱里谁醒透 在泉的叮咚里谁醉彻",
  "ru-ci": "花掉的妆要找谁赔 赔我一张面纸一杯水",
  "ren-a": "人啊多么地矛盾 人啊脆弱得不堪一击",
  "hao-jiu-bu-jian": "你会不会突然地出现 在街角的咖啡店",
  "xing-sailing": "I am sailing I am sailing",
  "bu-bi-zai-hu-wo-shi-shei": "几次真的想让自己醉 让自己远离那许多恩怨是非",
  "xia-yu-tian": "怎样的雨怎样的夜 怎样的我能让你更想念",
  "gen-ben-bu-shi-wo-dui-shou": "但是你根本不是我对手",
  "she-li-duan": "经过痴嗔贪 换得舍离断",
  "soap": "I'm tired of being careful gentle tring to \nKeep the water warm",
  "kuai-le-shi-yong-shou-ce": "在日月和星辰间漫步 我收集那孤独用快乐转述",
  "po-chen-shan": "I guess I will see you Sunday",
  "moon-talk": "I need to breath 想跟随月亮的轨迹靠近",
  "sunrise": "如果时光它有如果 我想要去对它诉说",
  "rnb-all-night": "R&B all night I just wanna R&B all night",
  "bie-wen-hen-ke-pa": "到底是怎样 别问很可怕",
  "ma-ma-shuo": "妈妈说 你路走得稳一些",
  "get-away": "我需要属于我的时间 逃离这个世界",
  "bu-zhi-de": "这感情不值得我犹豫 \n不值得我考虑 不值得我爱过你",
  "lang": "我害怕一到月圆时分 \n一转身一闪神 一下失去了方寸",
  "if-only": "如果只是梦 醒来再说",
  "zi-you": "我没有关系 你可以假装没事离开这里",
  "fu-er-mo-si": "爱情悬疑让人孤独 还催眠我这就是幸福",
  "nv-er-guo": "说什么王权富贵 怕什么戒律清规",
  "stand-by-me": "Darlin' darlin' stand by me oh stand by me",
  "ju-gao-zheng": "你让天空失去距离 我让我离开了迟疑",
  "ying-di": "可笑什么假装 无聊得去对自己表演",
  "ai-yu-tong-de-bian-yuan": "情像雨点似断难断 愈是去想更是凌乱",
  "lai-sheng-yuan": "也许分开不容易 也许相亲相爱不可以",
  "gao-shan-di-gu": "你快乐过生活 我拼命去生存",
  "san-ren-you": "一人留 两人疚 三人游",
  "fen-fen-zhong-xu-yao-ni": "我与你永共聚 分分钟需要你\n你似是阳光空气",
  "zhe-me-jin-na-me-yuan": "我留着你再身边 心仍然很远",
  "wei-ni-zhong-qing": "对我讲一声 I do I do 愿意一世让我高兴",
  "ai-shi-yong-heng": "有着我便有着你 真爱是永不死",
  "qian-yi-ge-ye-wan": "落寞的双眼 前面尚有千亿个夜晚",
  "ta-lai-ting-wo-de-yan-chang-hui": "我唱得她心碎 我唱得他心碎",
  "rang-ta-jiang-luo": "如果你能让她降落 天空如自由无尽头",
  "zui-chang-de-lv-tu": "随时间漂泊 随它忘了或记得",
  "ai-de-hui-gui-xian": "在爱的回归线 有期待终会有相见",
  "xuan-cao-hua": "高高的青山上 萱草花开放",
  "wo-yao-ni": "我要你在我身旁 我要看着你梳妆",
  "dian-qi-jiao-jian-ai": "想踮起脚尖找寻爱 远远的存在",
  "tai-yang-gong-zhu": "纯的笑泪的光 是全时空最真的假象",
  "ming-zhi-gu-wen": "你可以只回应我一个 躲闪的眼神\n我不会拿过去当作留住你的资本",
  "let-me-go": "Just let me go Please let me go",
  "gan-lan-shu": "不要问我从哪里来 我的故乡在远方",
  "gei-dian-ying-ren-de-qing-shu": "人间不过是你无心的梦 偶然留下的梦尘世梦"
};

const MOOD_CUES = {
  治愈: ["让声音把褶皱抚平", "适合安静听完的温度"],
  流行: ["旋律很快留下轮廓", "副歌里藏着情绪出口"],
  氛围: ["留白比答案更清晰", "适合戴上耳机慢慢听"],
  情绪: ["情绪沿着旋律逐层推进", "转折处最容易击中心事"],
  抒情: ["把没有说完的话唱完", "慢下来才听见细节"],
  轻快: ["节拍先一步点亮心情", "轻盈里也藏着小巧思"],
  叙事: ["像翻开一页声音日记", "故事感顺着旋律展开"],
  国风: ["古意与现代声线相遇", "余韵在尾音里慢慢散开"],
  "R&B": ["律动和转音彼此呼应", "适合跟着节拍轻轻摇摆"],
  摇滚: ["力量在层层推进中释放", "现场感让情绪更直接"],
  大气: ["声场一点点向远处打开", "高处的情绪更显辽阔"],
  律动: ["节拍让身体先于思考", "松弛感藏在每次落拍"],
  舞曲: ["舞台能量从第一拍启动", "适合跟着节奏直接进入"],
  明亮: ["旋律里透出一束亮色", "明快之外仍有细腻余味"],
  经典: ["熟悉旋律被唱出新质感", "把旧故事重新交给此刻"]
};

// 同一档音综共用一个本地封面 URL，浏览器只需解码和缓存一张图。
// 专辑曲和单曲仍保留各自封面，避免覆盖先行版、单曲版等差异。
const PROGRAM_COVER_IDS = {
  "综艺《歌手2025》": "li-bai-live",
  "综艺《2020中国好声音》": "xiang-feng-yi-yang",
  "综艺《天赐的声音》": "xia-yu-tian",
  "综艺《为歌而赞》": "soap",
  "综艺《说唱听我的》": "kuai-le-shi-yong-shou-ce",
  "综艺《爆裂舞台》": "rnb-all-night",
  "综艺《我们的歌》": "fu-er-mo-si",
  "综艺《声生不息·港乐季》": "ai-yu-tong-de-bian-yuan",
  "综艺《剧好听的歌》": "rang-ta-jiang-luo",
  "综艺《音乐缘计划》": "let-me-go",
  "综艺《国乐无双》": "gan-lan-shu",
  "演唱会": "weak-live",
  "晚会舞台": "zhe-shi-jie-na-me-duo-ren"
};

// 这些封面文件由维护者放在 assets/covers/nophoto/ 作为记录；
// 页面不请求该目录或同名 JPG，直接使用统一 default 图片。
const DEFAULT_COVER_IDS = new Set([
  "dong-bei-min-yao",
  "fei-yun-zhi-xia",
  "feng-xian",
  "shan-li-de-yang-guang",
  "song-ni-yi-duo-xiao-hong-hua",
  "tian-di-long-lin",
  "tian-tian",
  "tui-kai-shi-jie-de-men",
  "weak-live",
  "xiang-si",
  "yi-dong-de-xin",
  "zhe-shi-jie-na-me-duo-ren"
]);

window.SONG_CATALOG = rawSongs.map((row, index) => {
  const [id, title, source, vocal, mood, release, seedScore] = row;
  const color = SOURCE_META[source]?.colors || SOURCE_META.other.colors;
  const lyricExcerpt = HIGHLIGHT_LYRICS[id] || "";
  const coverId = PROGRAM_COVER_IDS[release] || id;
  return {
    id,
    title,
    source,
    sourceLabel: SOURCE_META[source]?.label || "其他",
    vocal,
    vocalLabel: vocal === "collab" ? "合作" : "独唱",
    mood,
    release,
    seedScore,
    cover: DEFAULT_COVER_IDS.has(coverId) ? "assets/covers/default.jpg" : `assets/covers/${coverId}.jpg`,
    lyricExcerpt,
    cardTextKind: lyricExcerpt ? "歌词短摘" : "听感提示",
    cardLines: lyricExcerpt ? [lyricExcerpt] : (MOOD_CUES[mood] || ["把注意力交给旋律", "听见属于它的独特颜色"]),
    quote: `这一刻，我把偏爱留给《${title}》。`,
    colors: index % 2 ? color : [color[1], color[0]]
  };
});

window.SONG_META = {
  source: Object.fromEntries(Object.entries(SOURCE_META).map(([key, value]) => [key, value.label])),
  vocal: { solo: "独唱", collab: "合作" }
};
